services:
  scraper:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pagar_scraper
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./data:/app/data
    networks:
      - webnet

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: pagar_nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - scraper
    networks:
      - webnet

networks:
  webnet:
    driver: bridge
